[package]
name = "orders"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "orders"
path = "src/main.rs"

[dependencies]
tonin-sdk = { workspace = true }
tokio    = { workspace = true }
tonic    = { workspace = true }
tonic-prost = { workspace = true }
prost    = { workspace = true }
tracing  = { workspace = true }

[build-dependencies]
tonin-build = { workspace = true }
