"""Generated by `cargo run --bin gen-shared-types`. DO NOT EDIT BY HAND.

Source of truth is the Rust types in `crates/tonin-client/src/`. Any
manual edit to this file will be reverted next time the generator runs.

The hand-written types in `auth.py`, `retry.py`, `breaker.py` are
kept here for the CI drift check — see `tests/test_generated_match.py`
in the tonin-client package.
"""

from __future__ import annotations

import enum
from dataclasses import dataclass, field
from typing import Any


class PrincipalKind(str, enum.Enum):
    """Who is making the call. Lowercase values match the Rust enum."""
    USER = "user"
    SERVICE = "service"
    AGENT = "agent"
    ANONYMOUS = "anonymous"

@dataclass(slots=True)
class RawToken:
    """A token as extracted from a request, before verification."""
    # The token string itself.
    value: str
    # Conventions: bearer-jwt, api-key, session-cookie, basic-auth.
    kind: str = "bearer-jwt"

@dataclass(slots=True)
class AuthCtx:
    """Identity + claims for the current request. The single concrete type that flows through the framework across languages."""
    # `sub` JWT claim. User ID for users, service ID for services.
    subject: str = ""
    # `iss` JWT claim.
    issuer: str = ""
    # `aud` JWT claim.
    audience: str = ""
    # OAuth-style scopes.
    scopes: list[str] = field(default_factory=list)
    # Principal class.
    kind: PrincipalKind = PrincipalKind.ANONYMOUS
    # Verbatim token, used by `propagate` on outbound calls.
    raw_token: str = ""
    # Unix-seconds expiry of the token.
    expires_at: float = 0.0
    # Custom claims not mapped to typed fields.
    extra: dict[str, Any] = field(default_factory=dict)

class Backoff(str, enum.Enum):
    """Retry backoff strategy."""
    EXPONENTIAL = "exponential"
    FIXED = "fixed"

@dataclass(slots=True)
class RetryPolicy:
    """Retry behavior for an outbound RPC. Same defaults as Rust."""
    # Total attempts including the first. 1 = no retry.
    max_attempts: int = 1
    # Delay before the first retry, in seconds.
    initial_backoff_secs: float = 0.0
    # Backoff growth strategy.
    backoff: Backoff = Backoff.FIXED
    # Exponential multiplier; ignored when backoff == FIXED.
    multiplier: float = 2.0
    # Cap on any single backoff interval, in seconds.
    max_backoff_secs: float = 1.0

@dataclass(slots=True)
class CircuitBreaker:
    """Breaker config for outbound RPCs. Same defaults as Rust."""
    # Rolling window for failure-rate calculation.
    window_secs: float = 10.0
    # Failure ratio in (0, 1] at which the breaker trips.
    trip_threshold: float = 0.5
    # Minimum requests in the window before the breaker can trip.
    min_requests: int = 20
    # How long the breaker stays Open before HalfOpen.
    reset_after_secs: float = 30.0
    # Probe requests allowed through in HalfOpen.
    half_open_probes: int = 3
