[package]
name = "inventory"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "inventory"
path = "src/main.rs"

[dependencies]
tonin           = { workspace = true }
tokio    = { workspace = true }
tonic    = { workspace = true }
prost    = { workspace = true }

[build-dependencies]
tonin-build = { workspace = true }
